/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Retrieves a list of RFQs matching filter criteria. Market makers can use this to poll RFQs directed to them.
 * Required minimum session key permission level is `read_only`
 */
export type PrivatePollRfqs = PrivatePollRfqsJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "private/poll_rfqs";
/**
 * Earliest `last_update_timestamp` to filter by (in ms since Unix epoch). If not provied, defaults to 0.
 */
export type FromTimestamp = number;
/**
 * Page number of results to return (default 1, returns last if above `num_pages`)
 */
export type Page = number;
/**
 * Number of results per page (default 100, max 1000)
 */
export type PageSize = number;
/**
 * RFQ ID filter, if applicable
 */
export type RfqId = string | null;
/**
 * Filter returned RFQs by rfq requestor subaccount
 */
export type RfqSubaccountId = number | null;
/**
 * RFQ status filter, if applicable
 */
export type Status = ("open" | "filled" | "cancelled" | "expired") | null;
/**
 * Subaccount ID for auth purposes, returned data will be scoped to this subaccount.
 */
export type SubaccountId = number;
/**
 * Latest `last_update_timestamp` to filter by (in ms since Unix epoch). If not provied, defaults to returning all data up to current time.
 */
export type ToTimestamp = number;
/**
 * Total number of items, across all pages
 */
export type Count = number;
/**
 * Number of pages
 */
export type NumPages = number;
/**
 * Cancel reason, if any
 */
export type CancelReason =
  | ""
  | "user_request"
  | "insufficient_margin"
  | "signed_max_fee_too_low"
  | "mmp_trigger"
  | "cancel_on_disconnect"
  | "session_key_deregistered"
  | "subaccount_withdrawn"
  | "rfq_no_longer_open"
  | "compliance";
/**
 * Creation timestamp in ms since Unix epoch
 */
export type CreationTimestamp = number;
/**
 * Direction at which the RFQ was filled (only if filled)
 */
export type FilledDirection = ("buy" | "sell") | null;
/**
 * Last update timestamp in ms since Unix epoch
 */
export type LastUpdateTimestamp = number;
/**
 * Amount in units of the base
 */
export type Amount = string;
/**
 * Leg direction
 */
export type Direction = "buy" | "sell";
/**
 * Instrument name
 */
export type InstrumentName = string;
/**
 * RFQ legs
 */
export type Legs = LegUnpricedSchema[];
/**
 * RFQ ID
 */
export type RfqId1 = string;
/**
 * Status
 */
export type Status1 = "open" | "filled" | "cancelled" | "expired";
/**
 * Subaccount ID
 */
export type SubaccountId1 = number;
/**
 * Total cost for the RFQ (only if filled)
 */
export type TotalCost = string | null;
/**
 * RFQ expiry timestamp in ms since Unix epoch
 */
export type ValidUntil = number;
/**
 * RFQs matching filter criteria
 */
export type Rfqs = RFQResultPublicSchema[];

export interface PrivatePollRfqsJSONRPCSchema {
  request: PrivatePollRfqsRequestSchema;
  response: PrivatePollRfqsResponseSchema;
}
export interface PrivatePollRfqsRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PrivatePollRfqsParamsSchema;
}
export interface PrivatePollRfqsParamsSchema {
  from_timestamp?: FromTimestamp;
  page?: Page;
  page_size?: PageSize;
  rfq_id?: RfqId;
  rfq_subaccount_id?: RfqSubaccountId;
  status?: Status;
  subaccount_id: SubaccountId;
  to_timestamp?: ToTimestamp;
}
export interface PrivatePollRfqsResponseSchema {
  id: string | number;
  result: PrivatePollRfqsResultSchema;
}
export interface PrivatePollRfqsResultSchema {
  pagination: PaginationInfoSchema;
  rfqs: Rfqs;
}
/**
 * Pagination info
 */
export interface PaginationInfoSchema {
  count: Count;
  num_pages: NumPages;
}
export interface RFQResultPublicSchema {
  cancel_reason: CancelReason;
  creation_timestamp: CreationTimestamp;
  filled_direction: FilledDirection;
  last_update_timestamp: LastUpdateTimestamp;
  legs: Legs;
  rfq_id: RfqId1;
  status: Status1;
  subaccount_id: SubaccountId1;
  total_cost: TotalCost;
  valid_until: ValidUntil;
}
export interface LegUnpricedSchema {
  amount: Amount;
  direction: Direction;
  instrument_name: InstrumentName;
}
