/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get trade history for a subaccount, with filter parameters.
 * Required minimum session key permission level is `read_only`
 */
export type PrivateGetTradeHistory = PrivateGetTradeHistoryJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "private/get_trade_history";
/**
 * Earliest timestamp to filter by (in ms since Unix epoch). If not provied, defaults to 0.
 */
export type FromTimestamp = number;
/**
 * Instrument name to filter by
 */
export type InstrumentName = string | null;
/**
 * Order id to filter by
 */
export type OrderId = string | null;
/**
 * Page number of results to return (default 1, returns last if above `num_pages`)
 */
export type Page = number;
/**
 * Number of results per page (default 100, max 1000)
 */
export type PageSize = number;
/**
 * If supplied, quote id to filter by. Supports either a concrete UUID, or `is_quote` and `is_not_quote` enum
 */
export type QuoteId = string | null;
/**
 * Subaccount_id (must be set if wallet is blank)
 */
export type SubaccountId = number | null;
/**
 * Latest timestamp to filter by (in ms since Unix epoch). If not provied, defaults to returning all data up to current time.
 */
export type ToTimestamp = number;
/**
 * Wallet address (if set, subaccount_id ignored)
 */
export type Wallet = string | null;
/**
 * Total number of items, across all pages
 */
export type Count = number;
/**
 * Number of pages
 */
export type NumPages = number;
/**
 * Subaccount ID requested, or 0 if not provided
 */
export type SubaccountId1 = number;
/**
 * Order direction
 */
export type Direction = "buy" | "sell";
/**
 * Index price of the underlying at the time of the trade
 */
export type IndexPrice = string;
/**
 * Instrument name
 */
export type InstrumentName1 = string;
/**
 * Whether the trade was generated through `private/transfer_position`
 */
export type IsTransfer = boolean;
/**
 * Optional user-defined label for the order
 */
export type Label = string;
/**
 * Role of the user in the trade
 */
export type LiquidityRole = "maker" | "taker";
/**
 * Mark price of the instrument at the time of the trade
 */
export type MarkPrice = string;
/**
 * Order ID
 */
export type OrderId1 = string;
/**
 * Quote ID if the trade was executed via RFQ
 */
export type QuoteId1 = string | null;
/**
 * Realized PnL for this trade
 */
export type RealizedPnl = string;
/**
 * Realized PnL for this trade using cost accounting that excludes fees
 */
export type RealizedPnlExclFees = string;
/**
 * Subaccount ID
 */
export type SubaccountId2 = number;
/**
 * Trade timestamp (in ms since Unix epoch)
 */
export type Timestamp = number;
/**
 * Amount filled in this trade
 */
export type TradeAmount = string;
/**
 * Fee for this trade
 */
export type TradeFee = string;
/**
 * Trade ID
 */
export type TradeId = string;
/**
 * Price at which the trade was filled
 */
export type TradePrice = string;
/**
 * The transaction id of the related settlement transaction
 */
export type TransactionId = string;
/**
 * Blockchain transaction hash
 */
export type TxHash = string | null;
/**
 * Blockchain transaction status
 */
export type TxStatus = "requested" | "pending" | "settled" | "reverted" | "ignored" | "timed_out";
/**
 * List of trades
 */
export type Trades = TradeResponseSchema[];

export interface PrivateGetTradeHistoryJSONRPCSchema {
  request: PrivateGetTradeHistoryRequestSchema;
  response: PrivateGetTradeHistoryResponseSchema;
}
export interface PrivateGetTradeHistoryRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PrivateGetTradeHistoryParamsSchema;
}
export interface PrivateGetTradeHistoryParamsSchema {
  from_timestamp?: FromTimestamp;
  instrument_name?: InstrumentName;
  order_id?: OrderId;
  page?: Page;
  page_size?: PageSize;
  quote_id?: QuoteId;
  subaccount_id?: SubaccountId;
  to_timestamp?: ToTimestamp;
  wallet?: Wallet;
}
export interface PrivateGetTradeHistoryResponseSchema {
  id: string | number;
  result: PrivateGetTradeHistoryResultSchema;
}
export interface PrivateGetTradeHistoryResultSchema {
  pagination: PaginationInfoSchema;
  subaccount_id: SubaccountId1;
  trades: Trades;
}
/**
 * Pagination info
 */
export interface PaginationInfoSchema {
  count: Count;
  num_pages: NumPages;
}
export interface TradeResponseSchema {
  direction: Direction;
  index_price: IndexPrice;
  instrument_name: InstrumentName1;
  is_transfer: IsTransfer;
  label: Label;
  liquidity_role: LiquidityRole;
  mark_price: MarkPrice;
  order_id: OrderId1;
  quote_id: QuoteId1;
  realized_pnl: RealizedPnl;
  realized_pnl_excl_fees: RealizedPnlExclFees;
  subaccount_id: SubaccountId2;
  timestamp: Timestamp;
  trade_amount: TradeAmount;
  trade_fee: TradeFee;
  trade_id: TradeId;
  trade_price: TradePrice;
  transaction_id: TransactionId;
  tx_hash: TxHash;
  tx_status: TxStatus;
}
