/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cancel all orders for this instrument.
 * Required minimum session key permission level is `admin`
 */
export type PrivateCancelAll = PrivateCancelAllJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "private/cancel_all";
export type SubaccountId = number;
export type Result = "ok";

export interface PrivateCancelAllJSONRPCSchema {
  request: PrivateCancelAllRequestSchema;
  response: PrivateCancelAllResponseSchema;
}
export interface PrivateCancelAllRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PrivateCancelAllParamsSchema;
}
export interface PrivateCancelAllParamsSchema {
  subaccount_id: SubaccountId;
}
export interface PrivateCancelAllResponseSchema {
  id: string | number;
  result: Result;
}
