/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get expired option settlement history for a subaccount
 * Required minimum session key permission level is `read_only`
 */
export type PrivateGetOptionSettlementHistory = PrivateGetOptionSettlementHistoryJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "private/get_option_settlement_history";
/**
 * Subaccount ID for which to get expired option settlement history
 */
export type SubaccountId = number;
/**
 * Amount that was settled
 */
export type Amount = string;
/**
 * Expiry timestamp of the option
 */
export type Expiry = number;
/**
 * Instrument name
 */
export type InstrumentName = string;
/**
 * USD profit or loss from option settlements calculated as: settlement value - (average cost including fees x amount)
 */
export type OptionSettlementPnl = string;
/**
 * USD profit or loss from option settlements calculated as: settlement value - (average price excluding fees x amount)
 */
export type OptionSettlementPnlExclFees = string;
/**
 * Price of option settlement
 */
export type SettlementPrice = string;
/**
 * Subaccount ID of the settlement event
 */
export type SubaccountId1 = number;
/**
 * List of expired option settlements
 */
export type Settlements = OptionSettlementResponseSchema[];
/**
 * Subaccount_id for which to get expired option settlement history
 */
export type SubaccountId2 = number;

export interface PrivateGetOptionSettlementHistoryJSONRPCSchema {
  request: PrivateGetOptionSettlementHistoryRequestSchema;
  response: PrivateGetOptionSettlementHistoryResponseSchema;
}
export interface PrivateGetOptionSettlementHistoryRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PrivateGetOptionSettlementHistoryParamsSchema;
}
export interface PrivateGetOptionSettlementHistoryParamsSchema {
  subaccount_id: SubaccountId;
}
export interface PrivateGetOptionSettlementHistoryResponseSchema {
  id: string | number;
  result: PrivateGetOptionSettlementHistoryResultSchema;
}
export interface PrivateGetOptionSettlementHistoryResultSchema {
  settlements: Settlements;
  subaccount_id: SubaccountId2;
}
export interface OptionSettlementResponseSchema {
  amount: Amount;
  expiry: Expiry;
  instrument_name: InstrumentName;
  option_settlement_pnl: OptionSettlementPnl;
  option_settlement_pnl_excl_fees: OptionSettlementPnlExclFees;
  settlement_price: SettlementPrice;
  subaccount_id: SubaccountId1;
}
