/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Retrieves a list of quotes matching filter criteria.<br />Takers can use this to poll open quotes that they can fill against their open RFQs.
 * Required minimum session key permission level is `read_only`
 */
export type PrivatePollQuotes = PrivatePollQuotesJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "private/poll_quotes";
/**
 * Earliest timestamp to filter by (in ms since Unix epoch). If not provied, defaults to 0.
 */
export type FromTimestamp = number;
/**
 * Page number of results to return (default 1, returns last if above `num_pages`)
 */
export type Page = number;
/**
 * Number of results per page (default 100, max 1000)
 */
export type PageSize = number;
/**
 * Quote ID filter, if applicable
 */
export type QuoteId = string | null;
/**
 * RFQ ID filter, if applicable
 */
export type RfqId = string | null;
/**
 * Quote status filter, if applicable
 */
export type Status = ("open" | "filled" | "cancelled" | "expired") | null;
/**
 * Subaccount ID for auth purposes, returned data will be scoped to this subaccount.
 */
export type SubaccountId = number;
/**
 * Latest timestamp to filter by (in ms since Unix epoch). If not provied, defaults to returning all data up to current time.
 */
export type ToTimestamp = number;
/**
 * Total number of items, across all pages
 */
export type Count = number;
/**
 * Number of pages
 */
export type NumPages = number;
/**
 * Cancel reason, if any
 */
export type CancelReason =
  | ""
  | "user_request"
  | "insufficient_margin"
  | "signed_max_fee_too_low"
  | "mmp_trigger"
  | "cancel_on_disconnect"
  | "session_key_deregistered"
  | "subaccount_withdrawn"
  | "rfq_no_longer_open"
  | "compliance";
/**
 * Creation timestamp in ms since Unix epoch
 */
export type CreationTimestamp = number;
/**
 * Quote direction
 */
export type Direction = "buy" | "sell";
/**
 * Last update timestamp in ms since Unix epoch
 */
export type LastUpdateTimestamp = number;
/**
 * Amount in units of the base
 */
export type Amount = string;
/**
 * Leg direction
 */
export type Direction1 = "buy" | "sell";
/**
 * Instrument name
 */
export type InstrumentName = string;
/**
 * Leg price
 */
export type Price = string;
/**
 * Quote legs
 */
export type Legs = LegPricedSchema[];
/**
 * Hash of the legs of the best quote to be signed by the taker.
 */
export type LegsHash = string;
/**
 * Liquidity role
 */
export type LiquidityRole = "maker" | "taker";
/**
 * Quote ID
 */
export type QuoteId1 = string;
/**
 * RFQ ID
 */
export type RfqId1 = string;
/**
 * Status
 */
export type Status1 = "open" | "filled" | "cancelled" | "expired";
/**
 * Subaccount ID
 */
export type SubaccountId1 = number;
/**
 * Blockchain transaction hash (only for executed quotes)
 */
export type TxHash = string | null;
/**
 * Blockchain transaction status (only for executed quotes)
 */
export type TxStatus = ("requested" | "pending" | "settled" | "reverted" | "ignored" | "timed_out") | null;
/**
 * Wallet address of the quote sender
 */
export type Wallet = string;
/**
 * Quotes matching filter criteria
 */
export type Quotes = QuoteResultPublicSchema[];

export interface PrivatePollQuotesJSONRPCSchema {
  request: PrivatePollQuotesRequestSchema;
  response: PrivatePollQuotesResponseSchema;
}
export interface PrivatePollQuotesRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PrivatePollQuotesParamsSchema;
}
export interface PrivatePollQuotesParamsSchema {
  from_timestamp?: FromTimestamp;
  page?: Page;
  page_size?: PageSize;
  quote_id?: QuoteId;
  rfq_id?: RfqId;
  status?: Status;
  subaccount_id: SubaccountId;
  to_timestamp?: ToTimestamp;
}
export interface PrivatePollQuotesResponseSchema {
  id: string | number;
  result: PrivatePollQuotesResultSchema;
}
export interface PrivatePollQuotesResultSchema {
  pagination: PaginationInfoSchema;
  quotes: Quotes;
}
/**
 * Pagination info
 */
export interface PaginationInfoSchema {
  count: Count;
  num_pages: NumPages;
}
export interface QuoteResultPublicSchema {
  cancel_reason: CancelReason;
  creation_timestamp: CreationTimestamp;
  direction: Direction;
  last_update_timestamp: LastUpdateTimestamp;
  legs: Legs;
  legs_hash: LegsHash;
  liquidity_role: LiquidityRole;
  quote_id: QuoteId1;
  rfq_id: RfqId1;
  status: Status1;
  subaccount_id: SubaccountId1;
  tx_hash: TxHash;
  tx_status: TxStatus;
  wallet: Wallet;
}
export interface LegPricedSchema {
  amount: Amount;
  direction: Direction1;
  instrument_name: InstrumentName;
  price: Price;
}
