/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cancel a single order by nonce. Uses up that nonce if the order does not exist, so any future orders with that nonce will fail
 * Required minimum session key permission level is `admin`
 */
export type PrivateCancelByNonce = PrivateCancelByNonceJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "private/cancel_by_nonce";
/**
 * Instrument name
 */
export type InstrumentName = string;
/**
 * Cancel an order with this nonce
 */
export type Nonce = number;
/**
 * Subaccount ID
 */
export type SubaccountId = number;
/**
 * Wallet address
 */
export type Wallet = string;
/**
 * Number of cancelled orders
 */
export type CancelledOrders = number;

export interface PrivateCancelByNonceJSONRPCSchema {
  request: PrivateCancelByNonceRequestSchema;
  response: PrivateCancelByNonceResponseSchema;
}
export interface PrivateCancelByNonceRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PrivateCancelByNonceParamsSchema;
}
export interface PrivateCancelByNonceParamsSchema {
  instrument_name: InstrumentName;
  nonce: Nonce;
  subaccount_id: SubaccountId;
  wallet: Wallet;
}
export interface PrivateCancelByNonceResponseSchema {
  id: string | number;
  result: PrivateCancelByNonceResultSchema;
}
export interface PrivateCancelByNonceResultSchema {
  cancelled_orders: CancelledOrders;
}
