/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cancels a single RFQ by id.
 * Required minimum session key permission level is `account`
 */
export type PrivateCancelRfq = PrivateCancelRfqJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "private/cancel_rfq";
/**
 * RFQ ID to cancel
 */
export type RfqId = string;
/**
 * Subaccount ID
 */
export type SubaccountId = number;
/**
 * The result of this method call, `ok` if successful
 */
export type Result = "ok";

export interface PrivateCancelRfqJSONRPCSchema {
  request: PrivateCancelRfqRequestSchema;
  response: PrivateCancelRfqResponseSchema;
}
export interface PrivateCancelRfqRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PrivateCancelRfqParamsSchema;
}
export interface PrivateCancelRfqParamsSchema {
  rfq_id: RfqId;
  subaccount_id: SubaccountId;
}
export interface PrivateCancelRfqResponseSchema {
  id: string | number;
  result: Result;
}
