/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PublicGetMatchingEngineMonitor = PublicGetMatchingEngineMonitorJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "public/get_matching_engine_monitor";
/**
 * Timestamp of incident in UTC sec
 */
export type CreationTimestampSec = number;
/**
 * Incident label
 */
export type Label = string;
/**
 * Incident message
 */
export type Message = string;
/**
 * Incident trigger type
 */
export type MonitorType = "manual" | "auto";
/**
 * Incident severity
 */
export type Severity = "low" | "medium" | "high";
/**
 * List of ongoing incidents related to matching engine
 */
export type Incidents = IncidentResponseSchema[];

export interface PublicGetMatchingEngineMonitorJSONRPCSchema {
  request: PublicGetMatchingEngineMonitorRequestSchema;
  response: PublicGetMatchingEngineMonitorResponseSchema;
}
export interface PublicGetMatchingEngineMonitorRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PublicGetMatchingEngineMonitorParamsSchema;
}
export interface PublicGetMatchingEngineMonitorParamsSchema {}
export interface PublicGetMatchingEngineMonitorResponseSchema {
  id: string | number;
  result: PublicGetMatchingEngineMonitorResultSchema;
}
export interface PublicGetMatchingEngineMonitorResultSchema {
  incidents: Incidents;
}
export interface IncidentResponseSchema {
  creation_timestamp_sec: CreationTimestampSec;
  label: Label;
  message: Message;
  monitor_type: MonitorType;
  severity: Severity;
}
