/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Used for getting a transaction by its transaction id
 */
export type PublicGetTransaction = PublicGetTransactionJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "public/get_transaction";
/**
 * transaction_id of the transaction to get
 */
export type TransactionId = string;
/**
 * Data used to create transaction
 */
export type Data = string;
/**
 * Error log if failed tx
 */
export type ErrorLog = string | null;
/**
 * Status of the transaction
 */
export type Status = "requested" | "pending" | "settled" | "reverted" | "ignored" | "timed_out";
/**
 * Transaction hash of a pending tx
 */
export type TransactionHash = string | null;

export interface PublicGetTransactionJSONRPCSchema {
  request: PublicGetTransactionRequestSchema;
  response: PublicGetTransactionResponseSchema;
}
export interface PublicGetTransactionRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PublicGetTransactionParamsSchema;
}
export interface PublicGetTransactionParamsSchema {
  transaction_id: TransactionId;
}
export interface PublicGetTransactionResponseSchema {
  id: string | number;
  result: PublicGetTransactionResultSchema;
}
export interface PublicGetTransactionResultSchema {
  data: Data;
  error_log: ErrorLog;
  status: Status;
  transaction_hash: TransactionHash;
}
