/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get all points for user across all programs. This request is cached in WSGI.
 */
export type Public = PublicJSONRPCSchema;
export type Method = "public/";
/**
 * Program for which to count points
 */
export type Program = string;
/**
 * Wallet address of the user
 */
export type Wallet = string;
/**
 * Flag user for special treatment
 */
export type Flag = string;
/**
 * Wallet address of referrer
 */
export type Parent = string;
/**
 * Percentage of total points earned by user
 */
export type PercentShareOfPoints = string;
export type Points1 = string;
/**
 * Total $ notional volume traded by the user in program
 */
export type TotalNotionalVolume = string;

export interface PublicJSONRPCSchema {
  request: PublicRequestSchema;
  response: PublicResponseSchema;
}
export interface PublicRequestSchema {
  id?: string | number;
  method: Method;
  params: PublicParamsSchema;
}
export interface PublicParamsSchema {
  program: Program;
  wallet: Wallet;
}
export interface PublicResponseSchema {
  id: string | number;
  result: PublicResultSchema;
}
export interface PublicResultSchema {
  flag: Flag;
  parent: Parent;
  percent_share_of_points: PercentShareOfPoints;
  points: Points;
  total_notional_volume: TotalNotionalVolume;
}
/**
 * Points earned per category
 */
export interface Points {
  [k: string]: Points1;
}
