/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get settlement prices by expiry for each currency
 */
export type PublicGetOptionSettlementPrices = PublicGetOptionSettlementPricesJSONRPCSchema;
export type HttpMethod = "GET";
export type Method = "public/get_option_settlement_prices";
/**
 * Currency for which to show expiries
 */
export type Currency = string;
/**
 * Expiry date in `YYYYMMDD` format
 */
export type ExpiryDate = string;
/**
 * Settlement price will show None if not yet settled onchain
 */
export type Price = string | null;
/**
 * UTC timestamp of expiry
 */
export type UtcExpirySec = number;
/**
 * List of expiry details
 */
export type Expiries = ExpiryResponseSchema[];

export interface PublicGetOptionSettlementPricesJSONRPCSchema {
  request: PublicGetOptionSettlementPricesRequestSchema;
  response: PublicGetOptionSettlementPricesResponseSchema;
}
export interface PublicGetOptionSettlementPricesRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PublicGetOptionSettlementPricesParamsSchema;
}
export interface PublicGetOptionSettlementPricesParamsSchema {
  currency: Currency;
}
export interface PublicGetOptionSettlementPricesResponseSchema {
  id: string | number;
  result: PublicGetOptionSettlementPricesResultSchema;
}
export interface PublicGetOptionSettlementPricesResultSchema {
  expiries: Expiries;
}
export interface ExpiryResponseSchema {
  expiry_date: ExpiryDate;
  price: Price;
  utc_expiry_sec: UtcExpirySec;
}
