/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get all vault assets held by user. Can query by smart contract address or smart contract owner.<br /><br />Includes VaultERC20Pool balances
 */
export type PublicGetVaultBalances = PublicGetVaultBalancesJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "public/get_vault_balances";
/**
 * If wallet not provided, can query balances by EOA that owns smart contract wallet
 */
export type SmartContractOwner = string | null;
/**
 * Ethereum wallet address of smart contract
 */
export type Wallet = string | null;
export type Address = string;
export type Amount = string;
export type ChainId = number;
export type Name = string;
export type VaultAssetType = string;
export type Result = VaultBalanceResponseSchema[];

export interface PublicGetVaultBalancesJSONRPCSchema {
  request: PublicGetVaultBalancesRequestSchema;
  response: PublicGetVaultBalancesResponseSchema;
}
export interface PublicGetVaultBalancesRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PublicGetVaultBalancesParamsSchema;
}
export interface PublicGetVaultBalancesParamsSchema {
  smart_contract_owner?: SmartContractOwner;
  wallet?: Wallet;
}
export interface PublicGetVaultBalancesResponseSchema {
  id: string | number;
  result: Result;
}
export interface VaultBalanceResponseSchema {
  address: Address;
  amount: Amount;
  chain_id: ChainId;
  name: Name;
  vault_asset_type: VaultAssetType;
}
