/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get all registered vault erc20 pools.
 */
export type PublicGetVaultPools = PublicGetVaultPoolsJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "public/get_vault_pools";
/**
 * On-chain address of the manager contract
 */
export type Address = string;
/**
 * Chain ID of vault pool contract
 */
export type ChainId = number;
/**
 * Name of the Vault ERC20 Pool
 */
export type Name = string;
/**
 * Pool contract type
 */
export type PoolType = "swell_simple_staking" | "non_socket_bridge";
export type Result = InternalCreateVaultErc20PoolResultSchema[];

export interface PublicGetVaultPoolsJSONRPCSchema {
  request: PublicGetVaultPoolsRequestSchema;
  response: PublicGetVaultPoolsResponseSchema;
}
export interface PublicGetVaultPoolsRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PublicGetVaultPoolsParamsSchema;
}
export interface PublicGetVaultPoolsParamsSchema {}
export interface PublicGetVaultPoolsResponseSchema {
  id: string | number;
  result: Result;
}
export interface InternalCreateVaultErc20PoolResultSchema {
  address: Address;
  chain_id: ChainId;
  name: Name;
  pool_type: PoolType;
}
