/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PublicGetLiveIncidents = PublicGetLiveIncidentsJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "public/get_live_incidents";
/**
 * Timestamp of incident in UTC sec
 */
export type CreationTimestampSec = number;
/**
 * Incident label
 */
export type Label = string;
/**
 * Incident message
 */
export type Message = string;
/**
 * Incident trigger type
 */
export type MonitorType = "manual" | "auto";
/**
 * Incident severity
 */
export type Severity = "low" | "medium" | "high";
/**
 * List of ongoing incidents
 */
export type Incidents = IncidentResponseSchema[];

export interface PublicGetLiveIncidentsJSONRPCSchema {
  request: PublicGetLiveIncidentsRequestSchema;
  response: PublicGetLiveIncidentsResponseSchema;
}
export interface PublicGetLiveIncidentsRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PublicGetLiveIncidentsParamsSchema;
}
export interface PublicGetLiveIncidentsParamsSchema {}
export interface PublicGetLiveIncidentsResponseSchema {
  id: string | number;
  result: PublicGetLiveIncidentsResultSchema;
}
export interface PublicGetLiveIncidentsResultSchema {
  incidents: Incidents;
}
export interface IncidentResponseSchema {
  creation_timestamp_sec: CreationTimestampSec;
  label: Label;
  message: Message;
  monitor_type: MonitorType;
  severity: Severity;
}
