/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Check the drift of a subaccount and return the drifted balances
 */
export type PublicCheckSubaccountDrift = PublicCheckSubaccountDriftJSONRPCSchema;
export type HttpMethod = "POST";
export type Method = "public/check_subaccount_drift";
/**
 * Subaccount ID
 */
export type SubaccountId = number;
export type DriftedBalances1 = string;
/**
 * List of drifted balances
 */
export type DriftedBalances = DriftedBalances1[];

export interface PublicCheckSubaccountDriftJSONRPCSchema {
  request: PublicCheckSubaccountDriftRequestSchema;
  response: PublicCheckSubaccountDriftResponseSchema;
}
export interface PublicCheckSubaccountDriftRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PublicCheckSubaccountDriftParamsSchema;
}
export interface PublicCheckSubaccountDriftParamsSchema {
  subaccount_id: SubaccountId;
}
export interface PublicCheckSubaccountDriftResponseSchema {
  id: string | number;
  result: PublicCheckSubaccountDriftResultSchema;
}
export interface PublicCheckSubaccountDriftResultSchema {
  drifted_balances: DriftedBalances;
}
