/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Calculates MtM and maintenance margin for a given subaccount.
 */
export type PublicMarginWatch = PublicMarginWatchJSONRPCSchema;
export type HttpMethod = "GET";
export type Method = "public/margin_watch";
/**
 * Force the fetching of on-chain balances, default False.
 */
export type ForceOnchain = boolean;
/**
 * Subaccount ID to get margin for.
 */
export type SubaccountId = number;
/**
 * Asset amount of given collateral
 */
export type Amount = string;
/**
 * Asset name
 */
export type AssetName = string;
/**
 * Type of asset collateral (currently always `erc20`)
 */
export type AssetType = "erc20" | "option" | "perp";
/**
 * USD value of collateral that contributes to initial margin
 */
export type InitialMargin = string;
/**
 * USD value of collateral that contributes to maintenance margin
 */
export type MaintenanceMargin = string;
/**
 * Current mark price of the asset
 */
export type MarkPrice = string;
/**
 * USD value of the collateral (amount * mark price)
 */
export type MarkValue = string;
/**
 * All collaterals that count towards margin of subaccount
 */
export type Collaterals = CollateralPublicResponseSchema[];
/**
 * Currency of subaccount
 */
export type Currency = string;
/**
 * Total initial margin requirement of all positions and collaterals.
 */
export type InitialMargin1 = string;
/**
 * Total maintenance margin requirement of all positions and collaterals.If this value falls below zero, the subaccount will be flagged for liquidation.
 */
export type MaintenanceMargin1 = string;
/**
 * Margin type of subaccount (`PM` (Portfolio Margin) or `SM` (Standard Margin))
 */
export type MarginType = "PM" | "SM";
/**
 * Position amount held by subaccount
 */
export type Amount1 = string;
/**
 * Asset delta (w.r.t. forward price for options, `1.0` for perps)
 */
export type Delta = string;
/**
 * Asset gamma (zero for non-options)
 */
export type Gamma = string;
/**
 * Current index (oracle) price for position's currency
 */
export type IndexPrice = string;
/**
 * USD initial margin requirement for this position
 */
export type InitialMargin2 = string;
/**
 * Instrument name (same as the base Asset name)
 */
export type InstrumentName = string;
/**
 * `erc20`, `option`, or `perp`
 */
export type InstrumentType = "erc20" | "option" | "perp";
/**
 * Index price at which position will be liquidated
 */
export type LiquidationPrice = string | null;
/**
 * USD maintenance margin requirement for this position
 */
export type MaintenanceMargin2 = string;
/**
 * Current mark price for position's instrument
 */
export type MarkPrice1 = string;
/**
 * USD value of the position; this represents how much USD can be recieved by fully closing the position at the current oracle price
 */
export type MarkValue1 = string;
/**
 * Asset theta (zero for non-options)
 */
export type Theta = string;
/**
 * Asset vega (zero for non-options)
 */
export type Vega = string;
/**
 * All active positions of subaccount
 */
export type Positions = PositionPublicResponseSchema[];
/**
 * Subaccount_id
 */
export type SubaccountId1 = number;
/**
 * Total mark-to-market value of all positions and collaterals
 */
export type SubaccountValue = string;
/**
 * Timestamp (in seconds since epoch) of when margin and MtM were computed.
 */
export type ValuationTimestamp = number;

export interface PublicMarginWatchJSONRPCSchema {
  request: PublicMarginWatchRequestSchema;
  response: PublicMarginWatchResponseSchema;
}
export interface PublicMarginWatchRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PublicMarginWatchParamsSchema;
}
export interface PublicMarginWatchParamsSchema {
  force_onchain?: ForceOnchain;
  subaccount_id: SubaccountId;
}
export interface PublicMarginWatchResponseSchema {
  id: string | number;
  result: PublicMarginWatchResultSchema;
}
export interface PublicMarginWatchResultSchema {
  collaterals: Collaterals;
  currency: Currency;
  initial_margin: InitialMargin1;
  maintenance_margin: MaintenanceMargin1;
  margin_type: MarginType;
  positions: Positions;
  subaccount_id: SubaccountId1;
  subaccount_value: SubaccountValue;
  valuation_timestamp: ValuationTimestamp;
}
export interface CollateralPublicResponseSchema {
  amount: Amount;
  asset_name: AssetName;
  asset_type: AssetType;
  initial_margin: InitialMargin;
  maintenance_margin: MaintenanceMargin;
  mark_price: MarkPrice;
  mark_value: MarkValue;
}
export interface PositionPublicResponseSchema {
  amount: Amount1;
  delta: Delta;
  gamma: Gamma;
  index_price: IndexPrice;
  initial_margin: InitialMargin2;
  instrument_name: InstrumentName;
  instrument_type: InstrumentType;
  liquidation_price: LiquidationPrice;
  maintenance_margin: MaintenanceMargin2;
  mark_price: MarkPrice1;
  mark_value: MarkValue1;
  theta: Theta;
  vega: Vega;
}
