/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get funding rate history. Start timestamp is restricted to at most 30 days ago.<br />End timestamp greater than current time will be truncated to current time.<br />Zero start timestamp is allowed and will default to 30 days from the end timestamp.<br /><br />DB: read replica
 */
export type PublicGetFundingRateHistory = PublicGetFundingRateHistoryJSONRPCSchema;
export type HttpMethod = "GET";
export type Method = "public/get_funding_rate_history";
/**
 * End timestamp of the event history (default current time)
 */
export type EndTimestamp = number;
/**
 * Instrument name to return funding history for
 */
export type InstrumentName = string;
/**
 * Period of the funding rate
 */
export type Period = 900 | 3600 | 14400 | 28800 | 86400;
/**
 * Start timestamp of the event history (default 0)
 */
export type StartTimestamp = number;
/**
 * Hourly funding rate value at the event time
 */
export type FundingRate = string;
/**
 * Timestamp of the funding rate update (in ms since UNIX epoch)
 */
export type Timestamp = number;
/**
 * List of funding rates
 */
export type FundingRateHistory = FundingRateSchema[];

export interface PublicGetFundingRateHistoryJSONRPCSchema {
  request: PublicGetFundingRateHistoryRequestSchema;
  response: PublicGetFundingRateHistoryResponseSchema;
}
export interface PublicGetFundingRateHistoryRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PublicGetFundingRateHistoryParamsSchema;
}
export interface PublicGetFundingRateHistoryParamsSchema {
  end_timestamp?: EndTimestamp;
  instrument_name: InstrumentName;
  period?: Period;
  start_timestamp?: StartTimestamp;
}
export interface PublicGetFundingRateHistoryResponseSchema {
  id: string | number;
  result: PublicGetFundingRateHistoryResultSchema;
}
export interface PublicGetFundingRateHistoryResultSchema {
  funding_rate_history: FundingRateHistory;
}
export interface FundingRateSchema {
  funding_rate: FundingRate;
  timestamp: Timestamp;
}
