/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get current socket bridge balance and latest accrued balance hours.<br /><br />Used to estimate Swell, EigenLayer and EtherFi points.
 */
export type PublicGetBridgeBalances = PublicGetBridgeBalancesJSONRPCSchema;
export type HttpMethod = "GET";
export type Method = "public/get_bridge_balances";
export type Balance = string;
export type BalanceHours = string;
export type ChainId = number;
export type Integrator = string;
export type Name = string;
export type Result = SocketBridgeBalanceResponseSchema[];

export interface PublicGetBridgeBalancesJSONRPCSchema {
  request: PublicGetBridgeBalancesRequestSchema;
  response: PublicGetBridgeBalancesResponseSchema;
}
export interface PublicGetBridgeBalancesRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: PublicGetBridgeBalancesParamsSchema;
}
export interface PublicGetBridgeBalancesParamsSchema {}
export interface PublicGetBridgeBalancesResponseSchema {
  id: string | number;
  result: Result;
}
export interface SocketBridgeBalanceResponseSchema {
  balance: Balance;
  balance_hours: BalanceHours;
  chain_id: ChainId;
  integrator: Integrator;
  name: Name;
}
