/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unsubscribe from a list of channels, or all channels.
 */
export type Unsubscribe = UnsubscribeJSONRPCSchema;
export type HttpMethod = null;
export type Method = "unsubscribe";
/**
 * A list of channels names to unsubscribe from.<br />If not provided, unsubscribe from all channels.
 */
export type Channels = Channels1[] | null;
export type Channels1 = string;
export type RemainingSubscriptions1 = string;
/**
 * A list of channels still subscribed to after the unsubscribe operation.
 */
export type RemainingSubscriptions = RemainingSubscriptions1[];
export type Status1 = string;

export interface UnsubscribeJSONRPCSchema {
  request: UnsubscribeRequestSchema;
  response: UnsubscribeResponseSchema;
}
export interface UnsubscribeRequestSchema {
  httpMethod: HttpMethod;
  id?: string | number;
  method: Method;
  params: UnsubscribeParamsSchema;
}
export interface UnsubscribeParamsSchema {
  channels?: Channels;
}
export interface UnsubscribeResponseSchema {
  id: string | number;
  result: UnsubscribeResultSchema;
}
export interface UnsubscribeResultSchema {
  remaining_subscriptions: RemainingSubscriptions;
  status: Status;
}
/**
 * A mapping of `channel`&nbsp;&#11106;&nbsp;`status`.<br />Successfully unsubscribed channels will have status `ok`.
 */
export interface Status {
  [k: string]: Status1;
}
